apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pg-db
  name: ebs-claim-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi